### ISSUE TITLE
Deployment/production issues

### ISSUE THREAD

**Issue by olevett** [Dean177/lunch#12]
When doing a deployment/production release, there are a couple of issues
- [x] Gulp requires Babel, which is a dev-dependency, so isn't available when doing `npm install --production`. The make command then fails preventing building
- [ ] `SET` in package.json (`SET NODE_ENV...`) is a Windowsy thing, so on a linux box just breaks things. I think setting environment variables should be handled by the OS running the app/outside of the Node script, and this might also simplify running things

**Comment by olevett** [comment]
Something else to consider is if we want to use Forever or something similar to make sure things stay vaguely up...and also any database configuration

**Comment by Dean177** [comment]
With regards to the dev dependecies; I'm not too concerned about everything just being a dependency this isnt a module so there is no benefit to doing 'npm install --production' rather than 'npm install'.

Re forever: When running in development (Nodemon)[https://github.com/remy/nodemon] is allready in use. This servers exactly the same purpose as 'Forever', with the added benefit of allowing environment variables to be set in an environment agnostic way which addresses the second point.
